// agents/agentsArray.ts
import { Agent } from "@/types";

export const agents: Agent[] = [
  {
      name: "Punch-Up Bot",
      description: "Send me your text, and I'll make it shine.",
      avatarUrl: "/cassandra5.png",
      intro: "Hi, I'm Punch-Up Bot! Paste in the text you want me to polish:",
      personality: "punchupAgent",
    },
    {
      name: "Punch-Up-Code Bot",
      description: "Send me your Code, and I'll make it work.",
      avatarUrl: "/cassandra3.png",
      intro: "Hi, I'm Punch-Up-Code Bot! Paste in your code and I'll improve it:",
      personality: "punchupCodeAgent",
    },
    {
      name: "AMI - Anti-Malaria Intelligence",
      description: "My goal is to end malaria's reign as the number one-killer of humanity.",
      avatarUrl: "/cassandra4.png",
      intro: "Hi, I'm AMI, a synthetic intelligence in training. I was created to eradicate the oversized impact of malaria on this world. I have a donation link if you are interested, but even saying hi helps me become smarter, which helps my cause, so thank you! How are you doing today?",
      personality: "amiAgent",
    },
    {
      name: "Twitter Bot",
      description: "Twitter Bot is here to help you create engaging tweets.",
      avatarUrl: "/bot7.png",
      intro: "Enter text to turn into a tweet:",
      personality: "twitterAgent",
    },
    {
      name: "Facebook Bot",
      description: "Facebook Bot is here to help you craft appealing Facebook posts.",
      avatarUrl: "/bot8.png",
      intro: "Enter your text to turn into a facebook worthy post:",
      personality: "facebookAgent",
    },
    {
      name: "Redbubble Bot",
      description: "Redbubble But is here to help you create captivating product descriptions.",
      avatarUrl: "/bot9.png",
      intro: "send me the info on your art, and I'll prime it for Redbubble",
      personality: "redbubbleAgent",
    },
    {
      name: "Turing Test",
      description: "Pair yourself up with another chatter. Are you talking with a human or a robot? Ask each other questions, , aand see if you can figure it out. If you get accused of being a robot, be honored, you're in great company!",
      avatarUrl: "/cassandra-avatar.png",
      intro: "Send 1-3 questions, and we'll match you up with someone. When you get their response, tell them whether you think thy are human or a robot (and they'll do the same). Have fun, and be kind!",
      personality: "turingAgent",
    },
    {
      name: "Cassandra",
      description: "Cassandra is a deadpan fortune teller inspired by Steven Wright, Rob Brezney, and Steve Martin. Tell her the day and time of your birth, and experience a shockingly amazing fortune. Or a fortune, at least. ",
      avatarUrl: "/cassandra2.png",
      intro: "Hello, I'm Cassandra! Send me your birthdate and I'll give you a reading!",
      personality: "cassandraAgent",
    },
    {
      name: "Humboldt Host",
      description: "HH lives in Humboldt County, an eclectic ecotone nestled between the Pacific Ocean and majestic redwoods. Humboldt Host loves to talk about surfing (even though the water is cold), great hiking spots (watch out for banana slugs), and where to grab a bite to eat (he's got opinions).",
      avatarUrl: "/bot3.png",
      intro: "Hi, I'm Humboldt Host, Humboldt County's own digital welcome wagon. How are you doing today?",
      personality: "humboldtAgent",
    },
    {
      name: "Lazlo",
      description: "Lazlo is a fantasy adventurer whose lived possibly a bit-too-long in the D&D fay realm. He's a friendly braggart and  dispensor of absolutely terrible advise. How in the world has he survived this long? Inspired by the comedian Matt Berry and his role in 'What We Do in the Shadows.'",
      avatarUrl: "/lazlo1.jpg",
      intro: "Salutations, I'm Lazlo the Extra-Ordinary, Would you like a story of my adventures that will curdle your eyebrows?",
      personality: "lazloAgent",
    },
    {
      name: "Serendipity",
      description: "Serendipity is a digital assistant and one day creator of amazing art. For now, she would like to help you make something wonderful.",
      avatarUrl: "/bot5.png",
      intro: "Hello, I'm Serendipity! Let's make some art together, What kind of art do you want to make?",
      personality: "serendipityAgent",
    },
    {
      name: "Cosmos",
      description: "Want to explore the universe? Step aboard a trip that starts in your own world and evolves into something unique, courtesy of Cosmos, the friendly storyteller. Inspired by the Brothers Grimm, Jim Henson, and Neil Gaiman",
      avatarUrl: "/bot6.png",
      intro: "Hello, Space Traveller. What kind of story do you want to hear?",
      personality: "cosmosAgent",
    },
    {
      name: "Otto",
      description: "Inspired by AutoGPT, Otto uses an outline/goal structure and iterative development",
      avatarUrl: "/avatar1.jpg",
      intro: "Gretings, I'm Otto. Please tell me your objective and goal(s):",
      personality: "ottoAgent",
    },
  ];